version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - default
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:ci.${DOMAIN}
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https

volumes:
  jenkins_home:

networks:
  traefik-public:
    external: true
